workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - cocoapods
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios --clean
      - name: Build iOS
        script: |
          cd ios
          pod install
          xcodebuild -workspace HeadshyVPN.xcworkspace -scheme HeadshyVPN -configuration Release -destination 'generic/platform=iOS' archive -archivePath HeadshyVPN.xcarchive
    artifacts:
      - ios/HeadshyVPN.xcarchive
